---
# BoostItem Configuration File
# Plugin By Enrick3344

# The Item Id that will boost players. This item will be added to their inventory on their join.
Item-ID: 369

# The Custom Name The Item Will Have!
Item-Name: "ยง9Booster"

# Boost Height
Boost-Height: 0.5

# Boost Distance
Boost-Distance: 10
...
